#include<iostream>
user namespace std;
int main()
{ 
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                   *                                                            "<<endl;
cout<<"                                              *   *   *                                                               "<<endl;
cout<<"                                          *      *       *                                                      "<<endl;
cout<<"                                      *         *           *                                                  "<<endl;
cout<<"                                  *            *               *                                               "<<endl;
cout<<"                              *               *                   *                                            "<<endl;
cout<<"                         *                   *                       *                                         "<<endl;
cout<<"                     *                      *                           *                                      "<<endl;
cout<<"                   *                       *                               *                                   "<<endl;
cout<<"                  *                       *                                   *                             "<<endl;   
cout<<"                 *                       *                                       *                                           "<<endl;
cout<<"                *                    *       *                                  * *                                          "<<endl;
cout<<"               *                 *               *                             *  *                                         "<<endl;
cout<<"              *              *                       *                        *   *                                       "<<endl;
cout<<"             *           *                               *                   *    *                                      "<<endl;
cout<<"            *        *                                       *              *     *                                     "<<endl;
cout<<"           *     *                                               *         *      *                                    "<<endl;
cout<<"          *  *                                                       *    *       *                                   "<<endl;
cout<<"         * ***************************************************************        *                            "<<endl;
cout<<"         *                                             **************    *        *                            "<<endl;
cout<<"         *                                             *     *      *    *        *                           "<<endl;
cout<<"         *                                             *     *      *    *        *                           "<<endl;
cout<<"         *                                             **************    *        *                           "<<endl;
cout<<"         *                                             *     *      *    *        *                           "<<endl;
cout<<"         *                                             *     *      *    *        *                           "<<endl;
cout<<"         *                                             **************    *        *                           "<<endl;
cout<<"         *                 ***********************                       *        *                                "<<endl;
cout<<"         *                 *                     *                       *        *                           "<<endl;
cout<<"         *                 *                     *                       *        *                           "<<endl;
cout<<"         *                 *                     *                       *        *                           "<<endl;
cout<<"         *                 *                     *                       *        *                           "<<endl;
cout<<"         *                 *                     *                       *        *                           "<<endl;
cout<<"         *                 *                     *                       *        *                           "<<endl;
cout<<"         *                 *                 (.) *                       *        *                            "<<endl;
cout<<"         *                 *                     *                       *       *                             "<<endl;
cout<<"         *                 *                     *                       *      *                              "<<endl;
cout<<"         *                 *                     *                       *     *                               "<<endl;
cout<<"         *                 *                     *                       *    *                                "<<endl;
cout<<"         *                 *                     *                       *   *                                 "<<endl;
cout<<"         *                 *                     *                       *  *                                  "<<endl;
cout<<"         *                 *                     *                       * *                                   "<<endl;
cout<<"         *****************************************************************                                                                                                    "<<endl;

cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
cout<<"                                                                                                             "<<endl;
}
